language: node_js
node_js:
  - "11"
script:
  - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - git clone https://${GITHUB_TOKEN}@github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git site
  - cp -R ./docs/data ./site/data/
  - ls -la
  - cd site
  - ls -la
  - git checkout ${GITHUB_BRANCH}
  - npm install
  - gatsby build
  - cd ..
  - cp ./docs/sitemap.xml ./site/public/sitemap.xml
  - cp ./docs/robots.txt ./site/public/robots.txt
  - cd site
  - firebase deploy --project ${FIREBASE_PROJECT} --token $FIREBASE_TOKEN
