language: node_js
node_js:
  - "11"
script:
  - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - git clone -b ${GITHUB_BRANCH} https://${GITHUB_TOKEN}@github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git
  - npm build
  - firebase deploy --project ${FIREBASE_PROJECT} --token $FIREBASE_TOKEN
