language: node_js
node_js:
  - "11"
script:
  - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - git clone https://${GITHUB_TOKEN}@github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git site
  - cd site
  - git checkout ${GITHUB_BRANCH} 
  - npm build
  - firebase deploy --project ${FIREBASE_PROJECT} --token $FIREBASE_TOKEN
