language: node_js
node_js:
  - "11"
script:
  - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - git clone https://${GITHUB_TOKEN}@github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git site
  - cp -R Elbrus-Bootcamp/Elbrus-Bootcamp/docs/data site/data/
  - cd site
  - git checkout ${GITHUB_BRANCH}
  - npm install
  - gatsby build
  - cd ..
  - cp Elbrus-Bootcamp/Elbrus-Bootcamp/docs/sitemap.xml site/public/sitemap.xml
  - cp Elbrus-Bootcamp/Elbrus-Bootcamp/docs/robots.txt site/public/robots.txt
  - cd site
  - firebase deploy --project ${FIREBASE_PROJECT} --token $FIREBASE_TOKEN
